application: Vane Chat
version: 1
deploy: true
pub: true
dart2js: true 

handlers:
- url: /ws
  match: exact 
  script: chat.dart
  handler: Chat
  
# Static content, will be served by your app's Nginx instance 
- url: /
  match: postregex
  static_dir: web

  
