name: Vane-Angular-Chat
framework: vane

handlers:
- url: /ws
  handler: chat.dart:Chat
  
# Static content, will be served by your app's Nginx instance 
- url: /
  match: postregex
  static_dir: web

# Equivalent longer config for the Dart handler above  
#- url: /ws
#  script: chat.dart
#  handler: Chat
 
